# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-13 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'hpc_module',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpc.Module')),
            ],
            options={
                'db_table': 'hpc_module_version',
                'ordering': ['id'],
            },
        ),
    ]
