# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-17 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpc', '0006_auto_20200117_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareversion',
            old_name='name',
            new_name='version',
        ),
    ]
