# Generated by Django 2.2.9 on 2020-02-05 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0008_auto_20200203_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('error', 'error')], default='info', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='security.LDAPUser')),
                ('to_ldap_imported_user', models.ManyToManyField(blank=True, to='security.LDAPUserImported')),
                ('to_ldap_user', models.ManyToManyField(blank=True, to='security.LDAPUser')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
