
# Generated by Django 1.11.10 on 2020-01-15 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpc', '0002_auto_20191216_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hpc_module_request',
                'ordering': ['id'],
            },
        ),
    ]
