
# Generated by Django 1.11.10 on 2020-01-15 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpc', '0003_modulerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulerequest',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='modulerequest',
            name='module',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='modulerequest',
            name='version',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='modulerequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
