# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-01-15 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpc', '0004_auto_20200115_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('website', models.URLField()),
                ('version', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('type', models.CharField(default='', max_length=128)),
                ('installation_guide', models.URLField()),
                ('motivation', models.TextField()),
                ('account', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hpc_software_request',
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='Module',
            new_name='Software',
        ),
        migrations.DeleteModel(
            name='ModuleRequest',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='module',
            new_name='software',
        ),
        migrations.AlterModelTable(
            name='software',
            table='hpc_software',
        ),
        migrations.AlterModelTable(
            name='version',
            table='hpc_software_version',
        ),
    ]
