
# Generated by Django 1.11.10 on 2020-01-17 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpc', '0005_auto_20200115_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Software',
            new_name='SoftwareInstalled',
        ),
        migrations.RenameModel(
            old_name='SoftwareRequest',
            new_name='SoftwareRequested',
        ),
        migrations.RenameModel(
            old_name='Version',
            new_name='SoftwareVersion',
        ),
        migrations.AlterModelTable(
            name='softwareinstalled',
            table='hpc_software_installed',
        ),
        migrations.AlterModelTable(
            name='softwarerequested',
            table='hpc_software_requested',
        ),
    ]
