
# Generated by Django 1.11.10 on 2020-01-17 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpc', '0007_auto_20200117_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwarerequested',
            old_name='name',
            new_name='software',
        ),
    ]
