
# Generated by Django 1.11.10 on 2020-01-24 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hpc', '0008_auto_20200117_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarerequested',
            name='requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
