
# Generated by Django 1.11.10 on 2018-12-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('usr', models.FloatField(max_length=100)),
                ('nice', models.FloatField(max_length=100)),
                ('sys', models.FloatField(max_length=100)),
                ('iowait', models.FloatField(max_length=100)),
                ('irq', models.FloatField(max_length=100)),
                ('soft', models.FloatField(max_length=100)),
                ('steal', models.FloatField(max_length=100)),
                ('guest', models.FloatField(max_length=100)),
                ('gnice', models.FloatField(max_length=100)),
                ('idle', models.FloatField(max_length=100)),
            ],
            options={
                'db_table': 'application___statistic___node',
                'ordering': ['id'],
            },
        ),
    ]
