# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import src.apps.home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('title_es', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('content_en', models.TextField(blank=True, default='', null=True)),
                ('content_es', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=src.apps.home.models.Document.___IMAGE_UPLOAD_TO___)),
            ],
            options={
                'db_table': 'application___home___document',
                'ordering': ['id'],
            },
        ),
    ]
